jenbuzz_elasticsearch_explorer_start:
    path:     /elasticsearchexplorer/
    controller: Jenbuzz\ElasticsearchExplorerBundle\Controller\DefaultController::index

jenbuzz_elasticsearch_explorer_search:
    path:     /elasticsearchexplorer/search/
    controller: Jenbuzz\ElasticsearchExplorerBundle\Controller\DefaultController::search

jenbuzz_elasticsearch_explorer_search_index:
    path:     /elasticsearchexplorer/search/{searchindex}/
    controller: Jenbuzz\ElasticsearchExplorerBundle\Controller\DefaultController::search

jenbuzz_elasticsearch_explorer_search_type:
    path:     /elasticsearchexplorer/search/{searchindex}/{searchtype}/
    controller: Jenbuzz\ElasticsearchExplorerBundle\Controller\DefaultController::search

jenbuzz_elasticsearch_explorer_search_term:
    path:     /elasticsearchexplorer/search/{searchindex}/{searchtype}/{searchfield}/{searchterm}/
    controller: Jenbuzz\ElasticsearchExplorerBundle\Controller\DefaultController::search

jenbuzz_elasticsearch_explorer_config:
    path:     /elasticsearchexplorer/config/
    controller: Jenbuzz\ElasticsearchExplorerBundle\Controller\DefaultController::config

jenbuzz_elasticsearch_explorer_plugins:
    path:     /elasticsearchexplorer/plugins/
    controller: Jenbuzz\ElasticsearchExplorerBundle\Controller\DefaultController::plugins
