dan_lyn_elasticsearch_explorer_start:
    path:     /elasticsearchexplorer/
    defaults: { _controller: DanLynElasticsearchExplorerBundle:Default:index }

dan_lyn_elasticsearch_explorer_search:
    path:     /elasticsearchexplorer/search/
    defaults: { _controller: DanLynElasticsearchExplorerBundle:Default:search }

dan_lyn_elasticsearch_explorer_search_index:
    path:     /elasticsearchexplorer/search/{index}/
    defaults: { _controller: DanLynElasticsearchExplorerBundle:Default:search }

dan_lyn_elasticsearch_explorer_search_type:
    path:     /elasticsearchexplorer/search/{index}/{type}/
    defaults: { _controller: DanLynElasticsearchExplorerBundle:Default:search }

dan_lyn_elasticsearch_explorer_search_term:
    path:     /elasticsearchexplorer/search/{index}/{type}/{searchterm}/
    defaults: { _controller: DanLynElasticsearchExplorerBundle:Default:search }
