services:
    DanLyn\ElasticsearchExplorerBundle\Elasticsearch\:
        resource: '../../Elasticsearch/*'

    DanLyn\ElasticsearchExplorerBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']