services:
    Jenbuzz\ElasticsearchExplorerBundle\Elasticsearch\:
        resource: '../../Elasticsearch/*'

    Jenbuzz\ElasticsearchExplorerBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']